### ISSUE TITLE
🐛 Made in Senegal Image not show

### ISSUE THREAD

**Issue by dofbi** [MedouneSGB/Waxtane#18]
Cc: @MedouneSGB 

Salut Team

### Image not show
https://waxtane.netlify.app/

![Capture d’écran du 2022-05-14 18-15-25](https://user-images.githubusercontent.com/84446/168443722-256b645b-f1a5-4763-989b-070513950aec.png)

Merci!

**Comment by MedouneSGB** [comment]
Hello je m'en occupe !

**Comment by MedouneSGB** [comment]
Hi Fixed ! ✨ 
Used html url format instead of markdown 

f6cdc15
45f9549
