### ISSUE TITLE
✨ If world not excite propose to add

### ISSUE THREAD

**Issue by dofbi** [MedouneSGB/Waxtane#19]
Cc: @MedouneSGB 

Salut Team
  
### Propose to add world
You search a world If no results found you have possibility to add the world

![Capture d’écran du 2022-05-14 18-17-16](https://user-images.githubusercontent.com/84446/168443863-921a5fc8-d23f-43c5-9886-6318413d2970.png)

Merci!

**Comment by MedouneSGB** [comment]
The fonctionnality is successfully implemented ! ✨ 
GG team lets solve and close the issue. ✅
