### ISSUE TITLE
🐍 Create a Python version of Waxtane.

### ISSUE THREAD

**Issue by MedouneSGB** [MedouneSGB/Waxtane#23]
Hi guys hope you're all well ! ✨

@Dar-rius proposed to make a python version of Waxtane.
Here is the issue to talk about it.

**Comment by Dar-rius** [comment]
Salut @dofbi  je voudrais savoir si ca te plait qu'on code le projet en python, c'est dans la branche python_version et voici la doc sur comment l'installer et faire marcher le serveur: https://github.com/MedouneSGB/Waxtane/blob/python_version/CONTRIBUTING.md

**Comment by MedouneSGB** [comment]
Salut, je pense que c'est mieux de garder la branche python en parallèle.

Je vais configurer le workflow pour qu'il le mette à jour aussi.

**Comment by dofbi** [comment]
Code or not code
Merci pour la contribution en python mais n'oublie pas la règle du DRY - don't repeat your self 🙏🏾

**Comment by Dar-rius** [comment]
D'accord
