### ISSUE TITLE
Fix Action CSV as DB

### ISSUE THREAD

**Issue by MedouneSGB** [MedouneSGB/Waxtane#7]
Bonjour l'action CSV to DB ne fonctionne pas correctement.
Quelqu'un peut il s'en charger.

**Comment by dofbi** [comment]
Hi @MedouneSGB 
Il te suffit d'update le fichier data/waxtane.csv
l'action crée les fichier 

- [README.md](https://github.com/MedouneSGB/Waxtane/blob/main/README.md)
- [Waxtane.md](https://github.com/MedouneSGB/Waxtane/blob/main/Waxtane.md)

à partir des templates

**Comment by MedouneSGB** [comment]
Hello @dofbi 
Certaine erreur sont parties, 
mais je n'ai pas pu passer le test #12

**Comment by MedouneSGB** [comment]
![image](https://user-images.githubusercontent.com/40875400/163858820-df3d437d-eb68-4f6c-b8ba-aeb19ba611a2.png)
J'ai fais le pull request depuis github.

**Comment by MedouneSGB** [comment]
Après quelques test il marche correctement !✅

**Comment by MedouneSGB** [comment]
Je pense pouvoir supprimer le fichier Waxtane.md.
Il devait remplir le même rôle que waxtane.csv.

**Comment by dofbi** [comment]
Hello @MedouneSGB 
Oui effectivement 

> Je pense pouvoir supprimer le fichier Waxtane.md.
> Il devait remplir le même rôle que waxtane.csv.

**Comment by MedouneSGB** [comment]
Done ✅
@dofbi je commence à appréhender l'énorme potentiel Workflow et de Github !
C'est vraiment fun ! 🔥😁

**Comment by MedouneSGB** [comment]
Think We can close this issue !
